import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google"

const inter = Inter({subsets:["latin"]})      // can use {inter.className} instead of {`${geistSans.variable} ${geistMono.variable} antialiased`} for className of the <body>

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>    
        <div className="p-4 border-b font-sans flex justify-center">
          Blog Website Header TopBar Common to All Routes (from app/layout.tsx)
        </div>
        {children}
      </body>
    </html>
  );
}
